= コーディングメモ

== app.py ではなく \\__init__.py で app を生成

次の二つを目的に \\__init__.py に記載している。

* アプリケーションのファクトリ(これは app.py でも良さそう)
* flaskr ディレクトリをパッケージとして扱うように指示

最終的にパッケージとして固めるために \\__init__.py に書いている模様。

== instance_relative_config(インスタンスフォルダ)

[source,python]
----
app = Flask(__name__, instance_relative_config=True)
----

[quote, DeepL 翻訳より]
____
instance_relative_config=True は、コンフィギュレーションファイルがインスタンスフォルダからの相対的なものであることをアプリに伝えます。
インスタンスフォルダは、 flaskr パッケージの外側にあり、コンフィギュレーションシークレットやデータベースファイルなど、バージョンコントロールにコミットすべきでないローカルデータを保持することができます。
____

インスタンスフォルダのデフォルトロケーションは次の通り。
https://flask.palletsprojects.com/en/2.0.x/config/#instance-folders[(Link)]

Uninstalled module::
+
--
....
/myapp.py
/instance
....
--
+
Uninstalled package::
+
--
....
/myapp
    /__init__.py
/instance
....
--

== app.config を設定する方法

いくつかある。
https://flask.palletsprojects.com/en/2.0.x/api/#configuration[(Link)]

[horizontal]
app.config.xxx = yyy:: 直接設定
app.config.from_envvar():: 引数に指定した .env をロード
app.config.from_file():: 引数に指定したファイルを、ロードする形式を指定してロード。 toml とか json とか指定できそう？
app.config.from_json():: 引数に指定した json ファイルをロード
app.config.from_mapping():: キーワード引数で任意の値を設定。また複数指定可能
app.config.from_pyfile():: 引数に指定した .py をロード

また各メソッドには silent が設定可能。
true にした場合はエラーを無視する(ファイルがない、など)。

== g (global), current_app

[horizontal]
g:: 1リクエストにおけるグローバル変数。 Object 型。
current_app:: 初期化した app を取得できる。つまり app.config などにアクセスできる。

[source,python]
.使用例 https://flask.palletsprojects.com/en/2.0.x/tutorial/database/#connect-to-the-database[(Link)]
----
import sqlite3

import click
from flask import current_app, g
from flask.cli import with_appcontext


def get_db():
    if 'db' not in g:
        g.db = sqlite3.connect(
            current_app.config['DATABASE'],
            detect_types=sqlite3.PARSE_DECLTYPES
        )
        g.db.row_factory = sqlite3.Row

    return g.db
----

== werkzeug.security が提供する generate_password_hash

[source,python]
----
from werkzeug.security import check_password_hash, generate_password_hash
----

werkzeug.security が提供する generate_password_hash は pbkdf2:sha256 によるハッシュ化。
単純にハッシュ化するわけではなく、ストレッチングによる難読化を施している。

wikipedia の記事より https://ja.wikipedia.org/wiki/PBKDF2[(Link)] 、 bcrypt と比較すると次のとおり。

[horizontal]
pbkdf2:sha256:: 処理は軽いがセキュリティは弱い
bcrypt:: 処理は重いがセキュリティは強い

なお、ここでいう「処理」とは「メモリ消費量」的な観点。
トレードオフなので積んでるメモリに応じて使い分けるとよさそう。

generate_password_hash で生成したハッシュは、 check_password_hash で検証可能。

== session への保存

[source,python]
----
from flask import session　# <1>

session.clear() # <2>
session['user_id'] = user['id'] # <3>
----
<1> session のインポート。 g とか current_app とかと同様に global な扱いの模様
<2> session の中身をクリア
<3> dict 形式でデータを格納

== ログインユーザーをグローバルに参照するテクニック

[source,python]
----
@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()
----

つまり。
リクエストのメイン処理前に前処理をフックして(before_app_request)、グローバル変数 g に格納する。
参照するときは g から user を参照することで、どこからでもグローバルに参照できる。

== 仮想環境へ開発用にプロジェクトをインストール

[quote, DeepL 翻訳より]
____
これは、pipにカレントディレクトリのsetup.pyを見つけさせ、編集可能モードまたは開発モードでインストールするように指示します。
編集可能モードとは、ローカルコードに変更を加えても、依存関係などのプロジェクトに関するメタデータを変更した場合にのみ、再インストールする必要があるということです。

プロジェクトがpip listでインストールされたことが確認できます。

これまでプロジェクトを実行してきた方法と何も変わりません。
FLASK_APPはflaskrに設定され、flask runはアプリケーションを実行しますが、flask-tutorialディレクトリだけでなく、どこからでも呼び出せるようになります。
____

[source,bash]
----
pip install -e .
# or
pipenv install -e .
----

「どこからでも呼び出せる」だけなら、仮想環境にインストールする必要なくない？という気もしたが。
なぜこれが必要かというと、 pytest を実行するにあたり root を特定するために必要。
なので、仮想環境にプロジェクトをインストールしないと pytest がプロジェクト(この場合は flaskr)の path を認識できない。

下記に「pytest が動かない」という issues があがっているが、上記が要因とのレスあり。
https://github.com/pallets/flask/issues/2908[Tutorial: Pytest don't find flaskr package #2908]


== app のコンテキスト

[source,python]
----
def test_get_close_db(app):
    with app.app_context():   # <1>
        db = get_db()
        assert db is get_db()

    with pytest.raises(sqlite3.ProgrammingError) as e:
        db.execute('SELECT 1')   # <2>

    assert 'closed' in str(e.value)
----
<1> with 句を用いることで conftest で生成している app のコンテキスト内で処理することを宣言
<2> with 句の外なので app のコンテキストは存在しない

== テストでセッションにアクセスする (pytest)

[quote, DeepL 翻訳より]
____
withブロックの中でclientを使うと、レスポンスが返ってきた後にsessionなどのコンテキスト変数にアクセスすることができます。
通常、リクエスト外でセッションにアクセスするとエラーになります。
____

[source,python]
----
def test_login(client, auth):
    assert client.get('/auth/login').status_code == 200
    response = auth.login()
    assert response.headers['Location'] == 'http://localhost/'

    with client:
        client.get('/')
        assert session['user_id'] == 1
        assert g.user['username'] == 'test'
----

== レスポンスの html の検証 (pytest)

`response.data` に html が含まれているため in 句を用いて検証できる。
なお `response.data` はバイナリで返る模様。

[source,python]
----
def test_index(client, auth):
    response = client.get('/')
    assert b"Log In" in response.data
    assert b"Register" in response.data
----
